swagger: '2.0'
info:
  description: |
    Barefoot nomad is an application that will enable its “Company Nomads” book their international travel and accommodation globally; easily and conveniently across all the locations/centers where the Company has its operations.
  version: 1.0.0
  title: Barefoot Nomad

tags:
  - name: Auth
    description: Authentication routes
host: localhost:3000
basePath: /api/v1
paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Logs in a user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User details
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        400:
          description: Invalid Credentials
        500:
          description: Unexpected Error
        200:
          description: Success
          schema:
            $ref: '#definitions/AuthReponse'
  /auth/signup:
    post:
      tags:
        - Auth
      summary: Create User Account
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User details
          required: true
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        409:
          description: Email already exists
        201:
          description: Success
          schema:
            $ref: '#definitions/AuthReponse'
  /auth/facebook:
    get:
      tags:
        - Auth
      summary: Logs in a user using facebook
      produces:
        - application/json
      responses:
        500:
          description: Unexpected Error
        400:
          description: Invalid Credentials
        200:
          description: Success
          schema:
            $ref: '#definitions/AuthReponse'
  /auth/google:
    get:
      tags:
        - Auth
      summary: Logs in a user using google
      produces:
        - application/json
      responses:
        500:
          description: Unexpected Error
        400:
          description: Invalid Credentials
        200:
          description: Success
          schema:
            $ref: '#definitions/AuthReponse'
  /auth/signup:
    post:
      tags:
        - Auth
      summary: Create User Account
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User details
          required: true
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        409:
          description: Email already exists
        201:
          description: Success
          schema:
            $ref: '#definitions/AuthReponse'

  /auth/verify?token:
    get:
      tags:
        - Auth
      summary: Verifies User Email
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: token
          description: User token
          required: true
          schema:
            type: string
            properties:
              email:
                type: string
      responses:
        400:
          description: Error
        200:
          description: Success
  /auth/resend_verification_link:
    post:
      tags:
        - Auth
      summary: Resend Verification Link
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: email
          description: User email
          required: true
          schema:
            type: string
            properties:
              email:
                type: string
      responses:
        400:
          description: error
        200:
          description: Success
  /auth/forgot_password:
    post:
      tags:
        - Auth
      summary: sends change mail paswword
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: email
          description: User Email
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
      responses:
        404:
          description: Email Not Found
        200:
          description: Success
  /auth/reset_password/{token}:
    patch:
      tags:
        - Auth
      summary: changes user password
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: password
          description: New password
          required: true
          schema:
            type: object
            properties:
              password:
                type: string
        - in: path
          name: token
          required: true
          type: string
      responses:
        404:
          description: Email Not Found
        200:
          description: Success
  
  /requests:
    get:
      tags:
        - Requests
      summary: Retrieve my requests
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: Authenticate User
          required: true
      responses:
        404:
          description: You've not make any requests
        401:
          description: Access Denied, No token provided
        200:
          description: Success
          schema:
            $ref: '#definitions/MyRequest'

  /requests/multi-city:
    post:
      tags:
        - Requests
      summary: Multi City Request
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: Authenticate User
          required: true
        - in: body
          name: body
          description: Multiple Request Destination
          required: true
          schema:
            properties:
              source:
                type: string
                required: true
              destination:
                type: string
              tripType:
                type: string
                required: true
              travelDate:
                type: string
                format: date
                required: true
              returnDate:
                type: string
                format: date
                required: true
              reason:
                type: string
              accommodation:
                type: string
      responses:
        400:
          description: The request cannot be empty
        401:
          description: Access Denied, No token provided
        200:
          description: Success
          schema:
            $ref: '#definitions/Request'

  /requests/one-way:
    post:
      tags:
        - Requests
      summary: Return Trip
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: Authenticate User
          required: truet
        - in: body
          name: body
          description: Trip request details
          required: true
          schema:
            type: object
            properties:
              source:
                type: string
              destination:
                type: string
              tripType:
                type: string
                description: Trip type
                enum:
                  - one-way
                  - return
                  - multi-city
              travelDate:
                type: string
                format: date-time
              returnDate:
                type: string
                format: date-time
              travelDate:
                type: string
              reason:
                type: string
              accommodation:
                type: string
      responses:
        201:
          description: success
          schema:
            $ref: '#/definitions/Request'
        400:
          description: Bad request
        401:
          description: Access Denied
        403:
          description: Authentication failed

  /requests/{requestId}:
    patch:
      tags:
        - Requests
      summary: Update request by id
      description: Updates a single request
      operationId: updateRequestById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: Authenticate User
          required: true
        - name: requestId
          in: path
          description: ID of request to update
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Updated request object
          required: true
          schema:
            type: object
            properties:
              source:
                type: string
              destination:
                type: string
              tripType:
                type: string
                description: Trip type
                enum:
                  - one-way
                  - return
                  - multi-city
              travelDate:
                type: string
                format: date-time
              returnDate:
                type: string
                format: date-time
              reason:
                type: string
              accommodation:
                type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Request'
        400:
          description: Bad request
        401:
          description: Access Denied
        403:
          description: Authentication failed
      security:
        - api_key: []

  /auth/assign_role:
    patch:
      tags:
        - Assign Role
      summary: Assign user role
      description: Assign user role with Super Administrator Access
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: roleId
          in: body
          description: Role ID 
          required: true
          type: integer
        - in: body
          name: email
          description: User email to be assigned a role
          required: true
          schema:
            type: object
            properties:
              email:
                type: string

      responses:
        200:
          description: successful operation
        400:
          description: Error
        401:
          description: Access Denied
        403:
          description: Authentication failed
      security:
        - api_key: []  

definitions:
  AuthReponse:
    properties:
      status:
        type: string
      data:
        type: object
        properties:
          token:
            type: string
          id:
            type: integer
          email:
            type: string
          firstName:
            type: string
          lastName:
            type: string
          isAdmin:
            type: boolean
            default: false
          isVerified:
            type: boolean
            default: false
  Request:
    properties:
      status:
        type: string
      data:
        type: object
        properties:
          id:
            type: integer
          source:
            type: string
            required: true
          destination:
            type: array
            items:
              type: string
            required: true
          type:
            type: string
          travelDate:
            type: string
            format: date
            required: true
          returnDate:
            type: string
            format: date
            required: true
          reason:
            type: string
          accommodation:
            type: string
          userId:
            type: integer
  MyRequest:
    properties:
      status:
        type: string
      data:
        type: array
        items:
          properties:
            id:
              type: integer
            source:
              type: string
              required: true
            destination:
              type: array
              items:
                type: string
              required: true
            type:
              type: string
            travelDate:
              type: string
              format: date
              required: true
            returnDate:
              type: string
              format: date
              required: true
            reason:
              type: string
            accommodation:
              type: string
            userId:
              type: integer

securityDefinitions:
  api_key:
    type: apiKey
    name: token
    in: header
definitions:
  Request:
    type: object
schemes:
  - https
  - http
  