swagger: '2.0'
info:
  description: |
    Barefoot nomad is an application that will enable its “Company Nomads” book their international travel and accommodation globally; easily and conveniently across all the locations/centers where the Company has its operations.
  version: 1.0.0
  title: Barefoot Nomad

tags:
  - name: Auth
    description: Authentication routes
host: localhost:3000
basePath: /api/v1
paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Logs in a user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User details
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        400:
          description: Invalid Credentials
        200:
          description: Success
          schema:
            $ref: '#definitions/AuthReponse'
  /auth/signup:
    post:
      tags:
        - Auth
      summary: Create User Account
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User details
          required: true
          schema:
            type: object
            properties:
              first_name:
                type: string
              last_name:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        409:
          description: Email already exists
        201:
          description: Success
          schema:
            $ref: '#definitions/AuthReponse'

  /auth/verify?token:
    get:
      tags:
        - Auth
      summary: Verifies User Email
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: token
          description: User token
          required: true
          schema:
            type: string
            properties:
              email:
                type: string
      responses:
        400:
          description: Error
        200:
          description: Success

  /auth/resend_verification_link:
    post:
      tags:
        - Auth
      summary: Resend Verification Link
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: email
          description: User email
          required: true
          schema:
            type: string
            properties:
              email:
                type: string
      responses:
        400:
          description: error
        200:
          description: Success
  /auth/forgot_password:
    post:
      tags:
        - Auth
      summary: sends change mail paswword
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: email
          description: User Email
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
      responses:
        404:
          description: Email Not Found
        200:
          description: Success
  /auth/reset_password/{token}:
    patch:
      tags:
        - Auth
      summary: changes user password
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: password
          description: New password
          required: true
          schema:
            type: object
            properties:
              password:
                type: string
        - in: path
          name: token
          required: true
          type: string
      responses:
        404:
          description: Email Not Found
        200:
          description: Success
          schema:
            $ref: '#definitions/AuthReponse'

  /request/multi-city:
    post:
      tags:
        - Request
      summary: Multi City Request
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: Authenticate User
          required: true
        - in: body
          name: body
          description: Multiple Request Destination
          required: true
          schema:
            properties:
              source:
                type: string
                required: true
              destination:
                type: array
                items:
                  type: string
              type:
                type: string
                required: true
              travel_date:
                type: string
                format: date
                required: true
              return_date:
                type: string
                format: date
                required: true
              reason:
                type: string
              accommodation:
                type: string
      responses:
        400:
          description: The request cannot be empty
        401:
          description: Access Denied, No token provided
        200:
          description: Success
          schema:
            $ref: '#definitions/MultiCityReponse'

definitions:
  AuthReponse:
    properties:
      status:
        type: string
      data:
        type: object
        properties:
          token:
            type: string
          id:
            type: integer
          email:
            type: string
          first_name:
            type: string
          last_name:
            type: string
          is_admin:
            type: boolean
            default: false
          is_verified:
            type: boolean
            default: false

  MultiCityReponse:
    properties:
      status:
        type: string
      data:
        type: object
        properties:
          id:
            type: integer
          source:
            type: string
            required: true
          destination:
            type: array
            items:
              type: string
            required: true
          type:
            type: string
          travel_date:
            type: string
            format: date
            required: true
          return_date:
            type: string
            format: date
            required: true
          reason:
            type: string
          accommodation:
            type: string
          user_id:
            type: integer

schemes:
  - https
  - http
