swagger: '2.0'
info:
  description: |
    Barefoot nomad is an application that will enable its “Company Nomads” book their international travel and accommodation globally; easily and conveniently across all the locations/centers where the Company has its operations.
  version: 1.0.0
  title: Barefoot Nomad
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

tags:
  - name: Auth
    description: Manage User Authentication
  - name: Users
    description: Manage User Account
host: localhost:3000
basePath: /api/v1
paths:
  /users/me:
    get:
      tags:
        - Users
      summary: View user's profile information
      description: View user's profile information
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: User authentication token
          required: true
          type: string
      responses:
        401:
          description: No token provided
          schema:
            $ref: '#definitions/ErrorResponse'
        400:
          description: Invalid token
          schema:
            $ref: '#definitions/ErrorResponse'
        200:
          description: Success
          schema:
            $ref: '#definitions/UsersResponse'
    patch:
      tags:
        - Users
      summary: Update user's profile information
      description: Update user's profile information
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: token
          description: User authentication token
          required: true
          type: string
        - in: body
          name: body
          description: Details to be updated
          required: true
          schema:
            type: object
            properties:
              first_name:
                type: string
              last_name:
                type: string
              gender:
                type: string
              date_of_birth:
                type: string
                format: date
              preferred_language:
                type: string
              residential_address:
                type: string
              preferred_currency:
                type: string
      responses:
        200:
          description: Success
          schema:
            $ref: '#definitions/UsersResponse'
        400:
          description: Bad request
          schema:
            $ref: '#definitions/ErrorResponse'
        401:
          description: No token provided
          schema:
            $ref: '#definitions/ErrorResponse'

  /auth/login:
    post:
      tags:
        - Auth
      summary: Logs in a user
      description: Logs in a user
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User details
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        400:
          description: Invalid Credentials
          schema:
            $ref: '#definitions/ErrorResponse'
        200:
          description: Success
          schema:
            $ref: '#definitions/AuthResponse'
  /auth/signup:
    post:
      tags:
        - Auth
      summary: Create User Account
      description: Creates a new user account
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User details
          required: true
          schema:
            type: object
            properties:
              first_name:
                type: string
              last_name:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        409:
          description: Email already exists
          schema:
            $ref: '#definitions/ErrorResponse'
        201:
          description: Success
          schema:
            $ref: '#definitions/AuthResponse'
definitions:
  AuthResponse:
    properties:
      status:
        type: string
      data:
        type: object
        properties:
          token:
            type: string
          id:
            type: integer
          email:
            type: string
            format: email
          first_name:
            type: string
          last_name:
            type: string
          is_admin:
            type: boolean
            default: false
          is_verified:
            type: boolean
            default: false
          role:
            type: string
            default: requester
          manager_id:
            type: integer
            nullable: true
          gender:
            type: string
            nullable: true
          date_of_birth:
            type: string
            format: date
            nullable: true
          department:
            type: string
            nullable: true
          preferred_language:
            type: string
            nullable: true
          residential_address:
            type: string
            nullable: true
          preferred_currency:
            type: string
            nullable: true
          createdAt:
            type: string
            format: date-time
          updatedAt:
            type: string
            format: date-time
  UsersResponse:
    properties:
      status:
        type: string
      data:
        type: object
        properties:
          id:
            type: integer
          email:
            type: string
            format: email
          first_name:
            type: string
          last_name:
            type: string
          is_admin:
            type: boolean
            default: false
          is_verified:
            type: boolean
            default: false
          role:
            type: string
            default: requester
          manager_id:
            type: integer
            nullable: true
          gender:
            type: string
            nullable: true
          date_of_birth:
            type: string
            format: date
            nullable: true
          department:
            type: string
            nullable: true
          preferred_language:
            type: string
            nullable: true
          residential_address:
            type: string
            nullable: true
          preferred_currency:
            type: string
            nullable: true
          createdAt:
            type: string
            format: date-time
          updatedAt:
            type: string
            format: date-time
  ErrorResponse:
    properties:
      status:
        type: string
      error:
        type: string
schemes:
  - https
  - http











