env:
  global:
    - CC_TEST_REPORTER_ID=646c778232b801f611ede9ea505ae8465fc4a2805589d6023afa890c243daf8d
node_js:
  - 'stable'
install:
  - npm install
  - npm install -g nyc
  - npm i -g sequelize-cli
cache:
directories:
  - 'node_modules'
addons:
  chrome: stable
  postgresql: 9.6
before_script:
  - psql -c 'create database icemantestdb;' -U postgres
  - npm run undo:migration
  - npm run db:migration
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
  - npm run coveralls
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
