language: node_js

node_js:
  - '10.15.1'

cache:
directories:
  - 'node_modules'

services:
  - postgresql

before_script:
  - psql -c 'create database icemantestdb;' -U postgres
  - npm i -g sequelize-cli

script:
  - npm run test

after_script:
  - npm run coverage
