language: node_js
node_js:
  - 'stable'
before_install:
  - npm update
install:
  - npm install
  - npm i -g sequelize-cli
cache:
directories:
  - 'node_modules'
services:
  - postgresql
before_script:
  - psql -c 'create database icemantest;' -U postgres
  - npm run test:dbscript
script:
  - npm run test
after_script:
  - npm run coverage
