language: node_js

node_js:
  - 'stable'

cache:
directories:
  - 'node_modules'

addons:
  chrome: stable
  postgresql: 9.6

before_script:
  - psql -c 'create database icemantest;' -U postgres
  - npm i -g sequelize-cli
  - npm run test:dbscript

script:
  - npm run test

after_script:
  - npm run coverage
