language: node_js
node_js:
  - 'stable'
before_install:
  - npm update
install:
  - npm install
cache:
directories:
  - 'node_modules'
addons:
  chrome: stable
  postgresql: 9.6
before_script:
  - psql -c 'create database gyrsurol;' -U postgres
  - npm i -g sequelize-cli
  - npm run db:migration
script:
  - npm test
after_script:
  - npm run coverage
  - npm run db:status

