export default {
    FACEBOOK_APP_ID: process.env.FACEBOOK_APP_ID,
    FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
    GOOGLE_CONSUMER_KEY: process.env.GOOGLE_CONSUMER_KEY,
    GOOGLE_CONSUMER_SECRET: process.env.GOOGLE_CONSUMER_SECRET
  
};
